spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 220984piv
    username: root
    url: jdbc:mysql://localhost:3306/trade
    data: classpath:data.sql
    initialization-mode: always


  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true


server:
  port: 8000
  servlet:
    context-path: /api
